--- 
before_script: 
  - "autopep8 -ir *"
  - "flake8 --max-complexity=15 --exclude=*.txt,*.md,*.pyc *"

install: "pip install -r requerimientos.txt"
language: python
python: 
  - "2.7"
script: 
  - "python TestEdades.py"
  - "coverage run --branch TestEdades.py"
  - "cd test"
  - "lettuce"
